[package]
name = "rustlib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", rev = "869a336fb981f4c676a0ccb6a9422fad95a4138e", features = [

] }
uuid = { version = "1.19.0", features = ["v4"] }
ahash = "0.8.12"
palette = "0.7.6"
image = "0.25.9"
rfd = "0.17.1"
indexmap = "2.12.1"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
echo = { path = "../../echo/echo" }
glam = "0.32.1"
directories = "6.0.0"
